### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by kleinash** [r2dbg/ConfParser.jl#6]
Hi,

I follow the instructions but get an error when trying to bring in an int:
```julia
[input]
height=28
width=28
```
So this imports ints as ::SubString{UTF8String}
and I do this to cast as Int:
```julia
width = Int(width)
```
but I get this error: 

LoadError: MethodError: `convert` has no method matching convert(::Type{Int64}, ::SubString{UTF8String})

Thx

**Comment by r2dbg** [comment]
@kleinash sorry for the late response.  The correct way to convert a substring to an integer in Julia is:
```julia
width = parse(Int, width)
```

**Comment by r2dbg** [comment]
I should also state that I am undecided as to whether or not I should add type detection logic to ConfParser and do the conversion for the user.  I feel it would be more practical to add another retrieve function for type specification.  Something like:
```julia
retrieve(conf, "width", Int)
```

**Comment by kleinash** [comment]
So you closed this which means its added? 

If there are sections to your .ini file then its something like: 

`width     = retrieve(conf, "depthimages", "width", Int)`
